import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;
import 'package:wise_clinical_camera/core/cv/lighting_engine.dart';
import 'package:wise_clinical_camera/core/cv/local_alignment_engine.dart';
import 'package:wise_clinical_camera/features/capture/capture_readiness.dart';
import 'package:wise_clinical_camera/models/enums.dart';

import '../support/cv_dataset.dart';

/// Clinical failure-mode analogues (Phase 2 sections 16-17, Computer Vision
/// sections 28-29, 60, 64).
///
/// Computer Vision section 64 lists what the engine must be tested against:
/// hair-bearing areas, dressings, shadows, lighting change and subject
/// movement. No clinical images were supplied and none may be committed
/// (Privacy section 52), so these are **synthetic analogues** that reproduce
/// the *structural* property that makes each case hard:
///
/// | Analogue | The property it reproduces |
/// |---|---|
/// | hair-like striations | dense, locally self-similar, highly repetitive |
/// | dressing | a large flat region with no features, appearing between visits |
/// | shadow | a strong spatial luminance gradient |
/// | gamma change | non-linear tone change, unlike a uniform offset |
/// | partial movement | no single rigid transform explains the frame |
///
/// An analogue is not a substitute. Real skin, real hair and real dressings
/// remain device test D-ALN-01..10. What these tests establish is that the
/// engine's *refusal* machinery engages on the right structural cues.
void main() {
  final findings = <String>[];

  tearDownAll(() {
    if (findings.isEmpty) return;
    final buffer = StringBuffer()
      ..writeln('# Clinical analogue results (synthetic)')
      ..writeln()
      ..writeln('Generated by `test/cv/clinical_analogue_test.dart`.')
      ..writeln()
      ..writeln('| Case | Outcome |')
      ..writeln('|---|---|');
    for (final finding in findings) {
      buffer.writeln(finding);
    }
    Directory('build').createSync(recursive: true);
    File('build/cv_analogues.md').writeAsStringSync(buffer.toString());
    // ignore: avoid_print
    print(buffer.toString());
  });

  Future<
    ({bool ready, bool available, double confidence, AlignmentStatus status})
  >
  align(img.Image reference, img.Image frame, String label) async {
    final engine = LocalAlignmentEngine();
    final prepared = await engine.prepareReference(
      photoId: 'ref',
      imageBytes: CvDataset.toJpeg(reference),
    );

    if (prepared.isFailure) {
      findings.add('| $label | reference refused (not alignable) |');
      return (
        ready: false,
        available: false,
        confidence: 0.0,
        status: AlignmentStatus.unavailable,
      );
    }

    final result = await engine.analyzeFrame(
      frame: CvDataset.toWorking(frame),
      reference: prepared.valueOrNull!,
    );

    findings.add(
      '| $label | ${result.status.wireName}, '
      'confidence ${result.confidence.toStringAsFixed(2)}, '
      'ready=${result.isReady} |',
    );

    return (
      ready: result.isReady,
      available: result.isAvailable,
      confidence: result.confidence,
      status: result.status,
    );
  }

  group('hair-bearing analogue', () {
    test('a shifted hair pattern does not report ready', () async {
      // Dense self-similar striations are the pattern most likely to produce
      // plausible but wrong correspondences.
      final hair = CvDataset.hairLike();
      final outcome = await align(
        hair,
        CvDataset.transform(hair, translateX: 24),
        'hair pattern, shifted 24px',
      );

      expect(
        outcome.ready,
        isFalse,
        reason: 'a shifted repetitive texture must never read as ready',
      );
    });

    test('two different hair patterns do not align confidently', () async {
      final outcome = await align(
        CvDataset.hairLike(seed: 1),
        CvDataset.hairLike(seed: 77, angle: -0.4),
        'two different hair patterns',
      );

      expect(outcome.ready, isFalse);
      expect(
        outcome.status,
        isNot(AlignmentStatus.good),
        reason: 'unrelated hair patterns must not read as a good match',
      );
    });
  });

  group('dressing analogue', () {
    test('a dressing covering half the frame lowers confidence', () async {
      final scene = CvDataset.texturedScene();

      final clear = await align(scene, scene, 'baseline, no dressing');
      final dressed = await align(
        scene,
        CvDataset.withDressing(scene),
        'dressing covering 45% of the frame',
      );

      expect(
        dressed.confidence,
        lessThan(clear.confidence),
        reason: 'removing half the visible detail must reduce confidence',
      );
    });

    test('a dressing covering almost everything is refused', () async {
      final scene = CvDataset.texturedScene();
      final outcome = await align(
        scene,
        CvDataset.withDressing(scene, coverage: 0.92),
        'dressing covering 92% of the frame',
      );

      expect(
        outcome.ready,
        isFalse,
        reason: 'almost no visible subject must not read as ready',
      );
    });
  });

  group('shadow analogue', () {
    test('a strong shadow does not produce a false good match', () async {
      final scene = CvDataset.texturedScene();
      final outcome = await align(
        scene,
        CvDataset.withShadow(scene),
        'strong directional shadow',
      );

      // A shadow does not move the subject, so alignment may legitimately
      // still succeed. What must not happen is a confident match on a frame
      // whose geometry actually differs.
      if (outcome.available) {
        expect(outcome.confidence, greaterThan(0));
      }
    });

    test('the lighting engine reports a shadow as different', () async {
      // Computer Vision section 41: a hard shadow redistributes the histogram
      // while barely moving the mean, which is why the histogram test exists
      // alongside the mean test.
      final scene = CvDataset.texturedScene();
      const engine = LightingEngine();

      final assessment = engine.compare(
        reference: CvDataset.toWorking(scene),
        frame: CvDataset.toWorking(CvDataset.withShadow(scene)),
      );

      findings.add(
        '| shadow, lighting check | ${assessment.status.wireName} '
        '(histogram similarity '
        '${assessment.histogramSimilarity.toStringAsFixed(2)}) |',
      );

      expect(assessment.status, LightingStatus.different);
    });
  });

  group('lighting change analogue', () {
    test('a gamma shift is reported as a lighting difference', () async {
      final scene = CvDataset.texturedScene();
      const engine = LightingEngine();

      final assessment = engine.compare(
        reference: CvDataset.toWorking(scene),
        frame: CvDataset.toWorking(CvDataset.withGamma(scene, 0.5)),
      );

      findings.add(
        '| gamma 0.5 (daylight vs lamp analogue) | '
        '${assessment.status.wireName} |',
      );

      expect(assessment.isWarning, isTrue);
    });

    test('alignment survives a moderate lighting change', () async {
      // Descriptors are intensity-comparison based, so they should be robust
      // to a monotonic tone change. If this ever regresses, the engine has
      // become brittle to ordinary clinic lighting.
      final scene = CvDataset.texturedScene();
      final outcome = await align(
        scene,
        CvDataset.withGamma(scene, 0.8),
        'alignment under gamma 0.8',
      );

      expect(
        outcome.available,
        isTrue,
        reason: 'a moderate tone change must not defeat alignment',
      );
    });
  });

  group('subject movement analogue', () {
    test('partial movement does not report ready', () async {
      // Computer Vision section 28: the system must distinguish camera
      // movement from subject movement. No single rigid transform explains a
      // frame where only half the content moved.
      final scene = CvDataset.texturedScene();
      final outcome = await align(
        scene,
        CvDataset.withPartialMovement(scene),
        'half the frame displaced (subject moved, camera did not)',
      );

      expect(
        outcome.ready,
        isFalse,
        reason:
            'when no single transform explains the frame, the engine must not '
            'report ready',
      );
    });
  });

  group('the checks combine to protect the user', () {
    test(
      'a shadow is caught by lighting even though alignment is happy',
      () async {
        // The measured behaviour: a strong shadow moves nothing, so the
        // alignment engine legitimately reports GOOD and its own isReady is
        // true. The lighting engine reports DIFFERENT. Neither is wrong.
        //
        // What matters is that CaptureReadiness combines them, so the clinician
        // is warned rather than told they are ready to reproduce a photograph
        // under visibly different light. This is the assertion that would fail
        // if someone ever wired readiness to alignment alone.
        final scene = CvDataset.texturedScene();
        final engine = LocalAlignmentEngine();
        final prepared = await engine.prepareReference(
          photoId: 'ref',
          imageBytes: CvDataset.toJpeg(scene),
        );
        final alignment = await engine.analyzeFrame(
          frame: CvDataset.toWorking(CvDataset.withShadow(scene)),
          reference: prepared.valueOrNull!,
        );
        final lighting = const LightingEngine().compare(
          reference: CvDataset.toWorking(scene),
          frame: CvDataset.toWorking(CvDataset.withShadow(scene)),
        );

        final readiness = CaptureReadiness.evaluate(
          alignment: alignment,
          lighting: lighting,
        );

        expect(lighting.isWarning, isTrue);
        expect(
          readiness.isReady,
          isFalse,
          reason:
              'a lighting warning must prevent the ready state even when the '
              'alignment engine is satisfied',
        );
        expect(
          readiness.canCapture,
          isTrue,
          reason: 'and it must still remain advisory',
        );

        findings.add(
          '| shadow, combined readiness | alignment '
          '${alignment.status.wireName} + lighting warning -> '
          'ready=${readiness.isReady}, canCapture=${readiness.canCapture} |',
        );
      },
    );
  });

  group('the honest summary', () {
    test('none of these analogues is clinical validation', () {
      // Recorded in the generated report so nobody reads the table as more
      // than it is (Computer Vision sections 44, 64, 78).
      findings.add(
        '| **status** | synthetic analogues only — not clinical validation |',
      );
      expect(findings, isNotEmpty);
    });
  });
}
